package com.example.newsly.ui.theme

import androidx.compose.ui.graphics.Color

//internal val primaryLight = Color(0xFF58B234)
//internal val primaryLight = Color(0xFF5f0f40)
internal val primaryLight = Color(0xFF0077b6)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFF64BF3F)
internal val onPrimaryContainerLight = Color(0xFF072500)
internal val secondaryLight = Color(0xFF04070C)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFF262A30)
internal val onSecondaryContainerLight = Color(0xFFB3B6BE)
internal val tertiaryLight = Color(0xFF265CB1)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFF85ADFF)
internal val onTertiaryContainerLight = Color(0xFF00214F)
internal val errorLight = Color(0xFFB12C16)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFF7A61)
internal val onErrorContainerLight = Color(0xFF350300)
internal val backgroundLight = Color(0xFFFFFFFF)
internal val onBackgroundLight = Color(0xFF181D14)
internal val surfaceLight = Color(0xFFFFFFFF)
internal val onSurfaceLight = Color(0xFF191D23)
internal val surfaceVariantLight = Color(0xFFE0E3E3)
internal val onSurfaceVariantLight = Color(0xFF5D5A6F)
internal val outlineLight = Color(0xFF747878)
internal val outlineVariantLight = Color(0xFFC4C7C8)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF313030)
internal val inverseOnSurfaceLight = Color(0xFFF4F0EF)
internal val inversePrimaryLight = Color(0xFF80DC59)
internal val surfaceDimLight = Color(0xFFDDD9D9)
internal val surfaceBrightLight = Color(0xFFFCF8F8)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF6F3F2)
internal val surfaceContainerLight = Color(0xFFF1EDEC)
internal val surfaceContainerHighLight = Color(0xFFEBE7E7)
internal val surfaceContainerHighestLight = Color(0xFFE5E2E1)